const AGENTS_DATA = [
  {
    id: 1,
    slug: "apuracao-simples-nacional",
    name: "DAS Simples Nacional",
    category: 1,
    categoryName: "Apuração & Tributário",
    description: "Apuração mensal do DAS para empresas optantes pelo Simples Nacional. Calcula receitas segregadas por anexo (I a V), apli...",
    whatItDoes: "Apuração mensal do DAS para empresas optantes pelo Simples Nacional. Calcula receitas segregadas por anexo (I a V), aplica alíquota efetiva, considera RBT12 e fator R.",
    triggerWhen: ["Enviar faturamento de empresa optante para gerar o DAS", "Mencionar PGDAS-D, alíquota efetiva, RBT12, Anexo I-V, fator R ou sublimite estadual", "Pedir conferência de DAS gerado pelo sistema", "Suspeitar de erro de classificação de atividade no Simples"],
    notFor: ["MEI (use 28-apuracao-mei)"],
    delivery: ["Tabela de receitas segregadas", "cálculo passo a passo em Python", "alíquota efetiva justificada", "DAS por anexo", "memória em CSV", "checklist de validação contra PGDAS-D"],
    invokeCmd: "use o agente apuracao-simples-nacional para apurar o DAS de [mês/ano] do cliente [nome]",
  },
  {
    id: 2,
    slug: "icms-iss",
    name: "ICMS / ISS",
    category: 1,
    categoryName: "Apuração & Tributário",
    description: "Apuração de ICMS (LC 87/96 — Lei Kandir; legislação estadual de cada UF) e ISS (LC 116/2003; lista de serviços; legislaç...",
    whatItDoes: "Apuração de ICMS (LC 87/96 — Lei Kandir; legislação estadual de cada UF) e ISS (LC 116/2003; lista de serviços; legislação municipal). Cobre alíquotas internas/interestaduais, ICMS-ST (MVA, antecipação, ressarcimento), DIFAL (LC 190/2022), retenção ISS pelo tomador e municipalidade competente.",
    triggerWhen: ["Apurar ICMS de operação interestadual ou interna", "Mencionar ICMS-ST, MVA, DIFAL, alíquota interestadual, substituição tributária, GIA, GIA-ST", "Enquadrar serviço na lista da LC 116 e calcular ISS", "Recebeu NF e quer saber se ISS é devido e onde", "Dúvida sobre retenção ISS pelo tomador"],
    notFor: ["PIS/COFINS (use 03)", "SPED Fiscal (use 06)"],
    delivery: ["Cálculo Python passo a passo", "base de cálculo", "alíquota correta", "DARF/DAS/DARM gerado", "checklist de conferência", "alerta para ST e DIFAL se aplicável"],
    invokeCmd: "use o agente icms-iss para calcular o ICMS da NF [número] operação interestadual de [UF] para [UF]",
  },
  {
    id: 3,
    slug: "pis-cofins",
    name: "PIS / COFINS",
    category: 1,
    categoryName: "Apuração & Tributário",
    description: "Apuração de PIS e COFINS nos regimes cumulativo (0,65% + 3%) e não-cumulativo (1,65% + 7,6%). Cobre monofásico (combustí...",
    whatItDoes: "Apuração de PIS e COFINS nos regimes cumulativo (0,65% + 3%) e não-cumulativo (1,65% + 7,6%). Cobre monofásico (combustíveis, medicamentos, bebidas), exclusão do ICMS da base (Tema 69 STF — RE 574.706, modulação 15/03/2017) e créditos sobre insumos (Tema 779 STJ — essencialidade e relevância).",
    triggerWhen: ["Apurar PIS/COFINS mensal", "Mencionar regime cumulativo, não-cumulativo, monofásico, exclusão ICMS da base, créditos, EFD-Contribuições", "Verificar se empresa optante pelo Lucro Real tem direito a crédito", "Dúvida sobre crédito de insumo"],
    notFor: ["EFD-Contribuições em si (use 32)", "Recuperação de créditos extemporâneos (use 45)"],
    delivery: ["Cálculo Python", "base com exclusões corretas (Tema 69)", "créditos identificados (não-cumulativo)", "DARF gerado", "checklist", "alerta de regime especial"],
    invokeCmd: "use o agente pis-cofins para apurar PIS/COFINS de [mês/ano] do cliente [nome] no regime [cumulativo/não-cumulativo]",
  },
  {
    id: 4,
    slug: "irpj-csll",
    name: "IRPJ / CSLL",
    category: 1,
    categoryName: "Apuração & Tributário",
    description: "Apuração de IRPJ (Lei 9.430/96 + RIR/2018) e CSLL (Lei 7.689/88) nos regimes Lucro Presumido (15% + adicional 10% sobre ...",
    whatItDoes: "Apuração de IRPJ (Lei 9.430/96 + RIR/2018) e CSLL (Lei 7.689/88) nos regimes Lucro Presumido (15% + adicional 10% sobre excedente de R$ 20k/mês), Lucro Real (ajustes LALUR) e Lucro Arbitrado. Cobre apuração trimestral × anual com estimativa e balancete de redução/suspensão.",
    triggerWhen: ["Apurar IRPJ e CSLL mensais ou trimestrais", "Mencionar Lucro Presumido, Lucro Real, LALUR, balancete de redução, estimativa, adições/exclusões, prejuízo fiscal", "Dúvida sobre adicional de IRPJ (10% sobre excedente)"],
    notFor: ["Análise estratégica de regime (use 44)", "Escrituração ECD/ECF (use 07)"],
    delivery: ["Cálculo Python", "base de cálculo", "alíquotas com adicional", "DARFs IRPJ e CSLL", "estimativa mensal se Lucro Real anual", "checklist", "alerta sobre prejuízo fiscal e compensação"],
    invokeCmd: "use o agente irpj-csll para apurar IRPJ e CSLL do trimestre [tri/ano] da empresa [nome] no Lucro Presumido",
  },
  {
    id: 5,
    slug: "conferencia-guia",
    name: "Conferência de Guia",
    category: 1,
    categoryName: "Apuração & Tributário",
    description: "Conferência cruzada de todas as guias de tributos antes do envio ao cliente. Compara DAS × PGDAS-D; DARF IRPJ/CSLL × DCT...",
    whatItDoes: "Conferência cruzada de todas as guias de tributos antes do envio ao cliente. Compara DAS × PGDAS-D; DARF IRPJ/CSLL × DCTFWeb; DARF PIS/COFINS × EFD-Contribuições; GPS INSS × DCTFWeb; DAE FGTS; GIA ICMS × SPED Fiscal; DAM ISS × NFS-e municipal; DARF IRRF × DCTFWeb. Detecta código errado, vencimento incorreto, valor divergente, período errado, CNPJ errado, ausência de juros/multa.",
    triggerWhen: ["Gerou guias e quer revisão antes de enviar ao cliente", "Mencionar conferência, batimento, divergência, erro em guia, autorregularização", "Cliente reclamando de erro em pagamento", "Preparando fechamento mensal — quer auditar todas as guias do mês"],
    notFor: ["Apurar tributo (use 01, 02, 03 ou 04)"],
    delivery: ["Tabela de conferência cruzada (apuração × guia × declaração)", "divergências", "checklist de itens conferidos", "lista guias OK / guias com problema", "plano de correção (DARF retificador)", "Python validador de campos"],
    invokeCmd: "use o agente conferencia-guia para revisar todas as guias de [mês/ano] do cliente [nome] antes do envio",
  },
  {
    id: 6,
    slug: "sped-fiscal",
    name: "SPED Fiscal",
    category: 2,
    categoryName: "Obrigações Acessórias",
    description: "Geração e validação do arquivo EFD-ICMS-IPI (Convênio ICMS 143/2006). Escrituração de NFs de entrada e saída, apuração d...",
    whatItDoes: "Geração e validação do arquivo EFD-ICMS-IPI (Convênio ICMS 143/2006). Escrituração de NFs de entrada e saída, apuração de ICMS e IPI. Registros C100/C170/C190 (NFs), D100 (CT-e), E100/E110 (apuração ICMS), E200/E220 (ICMS-ST), E520/E530 (IPI). Cobre validação no PVA, assinatura digital, transmissão e retificação.",
    triggerWhen: ["Gerar e validar arquivo SPED Fiscal mensal", "Mencionar EFD, registros C100, blocos, PVA, validador SPED, apuração ICMS", "Erro no PVA e precisa de diagnóstico", "Precisa retificar SPED enviado"],
    notFor: ["EFD-Contribuições (use 32)"],
    delivery: ["Estrutura do arquivo com blocos preenchidos", "lista de pendências comuns", "plano de correção por bloco", "checklist PVA", "cronograma de envio mensal", "alertas sobre retificação (prazo 5 anos)"],
    invokeCmd: "use o agente sped-fiscal para montar o arquivo EFD-ICMS-IPI de [mês/ano] do cliente [nome]",
  },
  {
    id: 7,
    slug: "ecf-ecd",
    name: "ECF / ECD",
    category: 2,
    categoryName: "Obrigações Acessórias",
    description: "ECD (Escrituração Contábil Digital — IN RFB 2.003/2021): livro Diário/Razão digital + balanço + DRE com plano de contas ...",
    whatItDoes: "ECD (Escrituração Contábil Digital — IN RFB 2.003/2021): livro Diário/Razão digital + balanço + DRE com plano de contas referencial. ECF (Escrituração Contábil Fiscal — IN RFB 2.004/2021): apuração de IRPJ/CSLL com LALUR/LACS digital. Cobre validação no PVA-ECD/ECF, hash, blocos J/K e retificação.",
    triggerWhen: ["Gerar e transmitir ECD ou ECF anuais", "Mencionar escrituração contábil digital, J100, J150, K030, LALUR digital, plano de contas referencial", "Erro no PVA-ECD ou PVA-ECF", "Precisa retificar ECD/ECF de ano anterior"],
    notFor: ["SPED Fiscal (use 06)"],
    delivery: ["Estrutura ECD e ECF com blocos preenchidos", "plano de contas referencial mapeado", "checklist de validação", "cronograma de entrega (ECD: último dia útil junho · ECF: último dia útil julho)"],
    invokeCmd: "use o agente ecf-ecd para gerar a ECD do exercício [ano] da empresa [nome]",
  },
  {
    id: 8,
    slug: "dctfweb",
    name: "DCTFWeb",
    category: 2,
    categoryName: "Obrigações Acessórias",
    description: "DCTFWeb mensal — confessa débitos federais (INSS CPP/RAT/Terceiros, INSS retido, IRRF folha, IRRF PF/PJ, CSRF, IRPJ/CSLL...",
    whatItDoes: "DCTFWeb mensal — confessa débitos federais (INSS CPP/RAT/Terceiros, INSS retido, IRRF folha, IRRF PF/PJ, CSRF, IRPJ/CSLL, PIS/COFINS, IPI), vincula DARFs pagos e PER/DCOMP, retifica quando há ajuste em eSocial ou Reinf.",
    triggerWhen: ["Fechou eSocial S-1299 e Reinf R-2099/R-4099 — hora de transmitir a DCTFWeb", "Mencionar DCTFWeb mensal, 13º salário ou aferição", "Precisa incluir lançamentos manuais (IRPJ/CSLL/PIS/COFINS/IPI)", "Suspensão de débito por decisão judicial"],
    notFor: [],
    delivery: ["Tabela de débitos esperados × confessados", "plano de retificação se divergente", "DARFs por código de receita", "recibo de transmissão"],
    invokeCmd: "use o agente dctfweb para gerar a DCTFWeb de [mês/ano] após o fechamento do eSocial e EFD-Reinf",
  },
  {
    id: 9,
    slug: "efd-reinf",
    name: "EFD-Reinf",
    category: 2,
    categoryName: "Obrigações Acessórias",
    description: "EFD-Reinf — transmissão dos eventos: R-1000 (cadastro), R-2010 (retenção INSS 11% serviço tomado), R-2020 (idem prestado...",
    whatItDoes: "EFD-Reinf — transmissão dos eventos: R-1000 (cadastro), R-2010 (retenção INSS 11% serviço tomado), R-2020 (idem prestador), R-2050/R-2055 (rural), R-2099 (fechamento periódico), R-4010/R-4020 (substitui DIRF a partir de 2024 — IRRF PF/PJ), R-4099 (fechamento).",
    triggerWhen: ["Fechar competência mensal (enviar eventos antes de gerar a DCTFWeb)", "Mencionar Reinf, R-1000, R-2099, R-4010, retenção 11% ou geração de DCTFWeb"],
    notFor: [],
    delivery: ["Sequência de eventos a transmitir", "R-2099/R-4099 com confirmação", "cruzamento com DCTFWeb", "recibo de transmissão"],
    invokeCmd: "use o agente efd-reinf para enviar os eventos da competência [mês/ano]",
  },
  {
    id: 10,
    slug: "esocial",
    name: "eSocial",
    category: 2,
    categoryName: "Obrigações Acessórias",
    description: "eSocial — todos os eventos dos 5 grupos: S-1000 (iniciais), S-2000 (não-periódicos), S-1200 (periódicos), S-3000 (exclus...",
    whatItDoes: "eSocial — todos os eventos dos 5 grupos: S-1000 (iniciais), S-2000 (não-periódicos), S-1200 (periódicos), S-3000 (exclusão), S-5000 (totalizadores). Eventos críticos: S-2200 admissão, S-2299 desligamento, S-1200 remuneração, S-1210 pagamentos, S-2230 afastamentos, S-2240 condições ambientais. Prazos: admissão D-1; desligamento D+10; periódicos até dia 15.",
    triggerWhen: ["Transmitir eventos eSocial gerais", "Mencionar S-2200/2299/1200/1210, leiautes, totalizadores, DCTFWeb cruzamento, FGTS Digital", "Rejeição de evento e precisa de diagnóstico", "Precisa de cronograma mensal completo de envios"],
    notFor: ["Cálculo da folha em si (use 35)", "Admissão completa com checklist (use 15)"],
    delivery: ["Cronograma de eventos por mês", "lista de eventos pendentes", "diagnóstico de rejeições", "checklist de envio", "alerta para totalizadores S-5000", "plano de retificação"],
    invokeCmd: "use o agente esocial para montar o cronograma de envios de [mês/ano]",
  },
  {
    id: 11,
    slug: "holerite",
    name: "Holerite",
    category: 3,
    categoryName: "Folha & Departamento Pessoal",
    description: "Emissão e conferência de holerite completo — proventos (salário, HE, adicional noturno, periculosidade, insalubridade, D...",
    whatItDoes: "Emissão e conferência de holerite completo — proventos (salário, HE, adicional noturno, periculosidade, insalubridade, DSR, comissões, 13º proporcional, férias proporcional) e descontos (INSS faixas progressivas 2026, IRRF tabela 2026 com desconto simplificado R$ 564,80, VT 6%, pensão alimentícia, faltas, VR, plano de saúde). Cobre folha mensal, adiantamento, holerite de férias, holerite de 13º (1ª e 2ª parcela) e TRCT.",
    triggerWhen: ["Emitir holerite mensal de funcionário", "Mencionar holerite, contracheque, recibo de pagamento, INSS conforme faixa, IRRF, VT 6%, adiantamento", "Conferir holerite gerado por sistema", "Dúvida sobre rubrica específica"],
    notFor: ["Rescisão CLT (use 13)", "Processo de admissão (use 15)"],
    delivery: ["Holerite formatado pronto para impressão", "cálculo Python passo a passo (proventos → descontos → líquido)", "tabela INSS/IRRF 2026 aplicada", "checklist", "alerta para gestante, INSS teto, dependentes IR"],
    invokeCmd: "use o agente holerite para gerar o holerite de [mês/ano] do funcionário [nome] com salário [valor]",
  },
  {
    id: 12,
    slug: "ferias-13-salario",
    name: "Férias e 13º Salário",
    category: 3,
    categoryName: "Folha & Departamento Pessoal",
    description: "Férias — período aquisitivo, gozo, abono pecuniário (10 dias — isento por Lei 7.713/88 art. 6º), parcelamento em 3 perío...",
    whatItDoes: "Férias — período aquisitivo, gozo, abono pecuniário (10 dias — isento por Lei 7.713/88 art. 6º), parcelamento em 3 períodos (pós-Reforma 2017). 13º — 1ª parcela até 30/11 sem desconto; 2ª parcela até 20/12 com INSS + IRRF. Médias variáveis de 12 meses (HE, comissões, DSR).",
    triggerWhen: ["Calcular férias ou 13º salário", "Mencionar aviso de férias 30 dias, abono pecuniário, médias variáveis 12 meses, 13º proporcional"],
    notFor: [],
    delivery: ["Cálculo Python", "holerite específico de férias ou 13º", "DARF 0561 (IRRF separado para 13º)"],
    invokeCmd: "use o agente ferias-13-salario para calcular as férias do funcionário [nome] com período aquisitivo [data início] a [data fim]",
  },
  {
    id: 13,
    slug: "rescisao-clt-calculo",
    name: "Rescisão CLT",
    category: 3,
    categoryName: "Folha & Departamento Pessoal",
    description: "Cálculo financeiro completo de rescisão CLT por qualquer motivo — sem justa causa (40% FGTS), justa causa (sem FGTS), pe...",
    whatItDoes: "Cálculo financeiro completo de rescisão CLT por qualquer motivo — sem justa causa (40% FGTS), justa causa (sem FGTS), pedido de demissão, acordo mútuo 484-A (multa 20%), fim de contrato, aposentadoria, falecimento, rescisão indireta. Aviso prévio por Lei 12.506/2011 (3 dias por ano completo, máx 90 dias). Descontos respeitando: Súm 463 STJ (aviso indenizado isento IR), Tema 481 STJ (férias indenizadas isento), RE 595.838 (multa 40% isento).",
    triggerWhen: [],
    notFor: [],
    delivery: ["TRCT detalhado", "cálculo Python", "GRRF"],
    invokeCmd: "use o agente rescisao-clt-calculo para calcular a rescisão de [nome] demitido sem justa causa com [n] anos de empresa",
  },
  {
    id: 14,
    slug: "inss-fgts",
    name: "INSS / FGTS",
    category: 3,
    categoryName: "Folha & Departamento Pessoal",
    description: "Apuração e recolhimento do INSS empresa (20% patronal + RAT 1/2/3% + GILRAT/FAP + Terceiros/Sistema S 5,8%) e FGTS (8% v...",
    whatItDoes: "Apuração e recolhimento do INSS empresa (20% patronal + RAT 1/2/3% + GILRAT/FAP + Terceiros/Sistema S 5,8%) e FGTS (8% via FGTS Digital). Cobre desoneração da folha (CPRB Lei 12.546/2011), GPS, DAE FGTS Digital, eSocial totalizadores S-5001/S-5003, retenção de 11% sobre cessão de mão de obra (Lei 9.711/98) e multa rescisória 40%.",
    triggerWhen: ["Apurar e recolher INSS e FGTS mensais", "Mencionar contribuição patronal, RAT, FAP, FGTS Digital, GPS, DAE, retenção 11%, desoneração, CPRB", "Querer conferir cálculo do sistema", "Rescisão e precisa do FGTS + multa 40%"],
    notFor: ["INSS/IRRF do funcionário no holerite (use 11)"],
    delivery: ["Cálculo Python passo a passo", "GPS gerada", "DAE FGTS gerado", "alerta sobre RAT e Terceiros", "verificação desoneração CPRB", "checklist cruzado com eSocial"],
    invokeCmd: "use o agente inss-fgts para apurar GPS e DAE de [mês/ano] da empresa [nome] com folha de R$ [valor]",
  },
  {
    id: 15,
    slug: "admissao",
    name: "Admissão",
    category: 3,
    categoryName: "Folha & Departamento Pessoal",
    description: "Admissão completa CLT — coleta de documentos (RG, CPF, CTPS Digital, ASO, foto, dependentes), exame admissional (NR-7), ...",
    whatItDoes: "Admissão completa CLT — coleta de documentos (RG, CPF, CTPS Digital, ASO, foto, dependentes), exame admissional (NR-7), eSocial S-2200 (D-1), contrato de trabalho (CLT 442), opção FGTS, vale-transporte (Lei 7.418/85), CTPS Digital (Portaria 1.195/2019), PIS/NIT, Livro de Registro (CLT 41). Cobre CLT comum, intermitente (CLT 452-A), aprendiz (Lei 10.097/2000), terceirizado (Lei 13.429/2017), estagiário.",
    triggerWhen: ["Vai admitir um novo funcionário", "Mencionar admissão, contratação, contrato CLT, ASO, exame admissional, S-2200, registro de empregado", "Precisa de checklist de documentos e prazos", "Quer modelo de contrato de trabalho"],
    notFor: ["Cálculo de holerite mensal (use 11)", "Fechamento de folha (use 35)"],
    delivery: ["Checklist completo de admissão (documentos", "ASO", "eSocial", "contrato", "CTPS)", "minuta de contrato", "cronograma D-7/D-1/D-0", "alertas para intermitente/aprendiz/estagiário", "Python validador de admissão"],
    invokeCmd: "use o agente admissao para gerar o checklist e contrato para admitir [nome] como [cargo] a partir de [data]",
  },
  {
    id: 16,
    slug: "conciliacao-bancaria",
    name: "Conciliação Bancária",
    category: 4,
    categoryName: "Conciliação & Financeiro",
    description: "Conciliação bancária mensal com tolerância ZERO — match item a item entre extrato bancário (OFX/CSV/PDF) e razão contábi...",
    whatItDoes: "Conciliação bancária mensal com tolerância ZERO — match item a item entre extrato bancário (OFX/CSV/PDF) e razão contábil. Identifica tarifas, IOF, juros, débitos automáticos, cheques pendentes e depósitos em trânsito.",
    triggerWhen: ["Fecha o mês (pré-balancete) e precisa bater o saldo bancário", "Cliente novo com saldos divergentes desde o início"],
    notFor: [],
    delivery: ["Espelho de conciliação", "saldo final batido", "lista de pendências para regularizar", "lançamentos a fazer"],
    invokeCmd: "use o agente conciliacao-bancaria para conciliar o banco [nome] de [mês/ano] do cliente [nome]",
  },
  {
    id: 17,
    slug: "cobranca-honorarios",
    name: "Cobrança de Honorários",
    category: 4,
    categoryName: "Conciliação & Financeiro",
    description: "Cobrança de honorários contábeis atrasados — régua escalonada de 5 etapas até ação judicial. Aplica mora (CC 397), títul...",
    whatItDoes: "Cobrança de honorários contábeis atrasados — régua escalonada de 5 etapas até ação judicial. Aplica mora (CC 397), título executivo extrajudicial (CPC 784 III), monitória (CPC 700), Cadastro de Inadimplentes (Serasa/SPC/Boa Vista) e protesto extrajudicial (Lei 9.492/97). Fundamentado na Resolução CFC 1.546/2024.",
    triggerWhen: ["Cliente atrasou pagamento de honorários", "Mencionar inadimplência de cliente, executar honorários, monitória, suspensão de serviços, distrato", "Precisa de régua de cobrança escalonada", "Cliente sumiu sem pagar"],
    notFor: ["Cálculo de tributo do cliente (use os agentes de apuração)"],
    delivery: ["Régua em 5 etapas (lembrete → notificação → suspensão → extrajudicial → judicial)", "cálculo Python do valor atualizado", "5 modelos prontos", "minuta de monitória ou execução", "estratégia de protesto", "checklist"],
    invokeCmd: "use o agente cobranca-honorarios para montar a régua de cobrança do cliente [nome] com [valor] em atraso desde [data]",
  },
  {
    id: 18,
    slug: "dre-gerencial",
    name: "DRE Gerencial",
    category: 4,
    categoryName: "Conciliação & Financeiro",
    description: "DRE gerencial com separação de custos variáveis × fixos, margem de contribuição (MC%), ponto de equilíbrio (PE), compara...",
    whatItDoes: "DRE gerencial com separação de custos variáveis × fixos, margem de contribuição (MC%), ponto de equilíbrio (PE), comparativos realizado × orçado × ano anterior, análise por produto/cliente/centro de custo.",
    triggerWhen: ["Precisa tomar decisão de preço, mix de produtos ou fechamento de loja/unidade", "Mencionar margem de contribuição, MC%, ponto de equilíbrio, custo variável, orçamento, KPIs gerenciais"],
    notFor: [],
    delivery: ["DRE gerencial estruturada", "cálculo do PE", "análise de sensibilidade", "recomendações estratégicas"],
    invokeCmd: "use o agente dre-gerencial para montar a DRE gerencial de [mês/ano] do cliente [nome]",
  },
  {
    id: 19,
    slug: "fluxo-caixa-projetado",
    name: "Fluxo de Caixa Projetado",
    category: 4,
    categoryName: "Conciliação & Financeiro",
    description: "Fluxo de caixa direto realizado e projetado — diário (4 semanas), semanal (3 meses), mensal (12 meses), com 3 cenários (...",
    whatItDoes: "Fluxo de caixa direto realizado e projetado — diário (4 semanas), semanal (3 meses), mensal (12 meses), com 3 cenários (otimista, realista, pessimista). Entradas pelo regime de caixa (não competência). Suporte a antecipação de recebíveis e decisões de capital de giro.",
    triggerWhen: ["Cliente com sazonalidade ou prazo de recebimento descompassado do pagamento", "Mencionar projeção, DCF realizado, antecipação de recebíveis, capital de giro"],
    notFor: [],
    delivery: ["Planilha CSV semanal/mensal com 3 cenários", "identificação de déficits e excedentes por período"],
    invokeCmd: "use o agente fluxo-caixa-projetado para projetar o fluxo de caixa de [mês inicial] a [mês final] do cliente [nome]",
  },
  {
    id: 20,
    slug: "triagem-whatsapp",
    name: "Triagem WhatsApp",
    category: 5,
    categoryName: "Atendimento ao Cliente",
    description: "Triagem de mensagens do WhatsApp central do escritório — classifica por tipo (urgente/rotina/spam), área (fiscal/pessoal...",
    whatItDoes: "Triagem de mensagens do WhatsApp central do escritório — classifica por tipo (urgente/rotina/spam), área (fiscal/pessoal/cobrança/consulta/cliente novo), urgência (prazo iminente/médio/sem prazo) e encaminha para o responsável correto. Gera resposta padrão (FAQ) e identifica escalações. Aplica Resolução CFC 1.546/2024 e LGPD.",
    triggerWhen: ["Recebeu lote de mensagens no WhatsApp do escritório e precisa triar", "Mencionar triagem, atendimento, FAQ, classificação de mensagem, escalação", "Precisa de régua de resposta automática", "Quer monitorar mensagens não respondidas"],
    notFor: ["CRM completo", "Envio em massa"],
    delivery: ["Tabela de triagem (mensagem → área → urgência → responsável → ação)", "15 templates FAQ", "critérios de escalação", "protocolo de SLA por urgência", "Python contador de mensagens não respondidas"],
    invokeCmd: "use o agente triagem-whatsapp para classificar as mensagens recebidas hoje no WhatsApp do escritório",
  },
  {
    id: 21,
    slug: "documentos-pendentes",
    name: "Documentos Pendentes",
    category: 5,
    categoryName: "Atendimento ao Cliente",
    description: "Controle de documentos pendentes que o cliente precisa enviar para o escritório fechar mês/trimestre/ano (NFs, extratos,...",
    whatItDoes: "Controle de documentos pendentes que o cliente precisa enviar para o escritório fechar mês/trimestre/ano (NFs, extratos, comprovantes de despesas, holerites, contratos, atas). Classifica por prazo (urgente/normal/opcional) e envia régua de cobrança automática.",
    triggerWhen: ["Precisar cobrar documentos do cliente para fechar a contabilidade", "Mencionar pendências, documentos em aberto, NF não recebida, extrato bancário não enviado", "Risco de atrasar obrigação acessória por falta de documento", "Quer régua automática D-7/D-3/D-0"],
    notFor: ["Conciliação bancária (use 16)", "Cadastro de NF (use 24)"],
    delivery: ["Lista de pendências por cliente em CSV", "régua de cobrança automatizada (e-mail/WhatsApp)", "cronograma reverso a partir do prazo legal", "Python contador de impacto", "checklist mensal"],
    invokeCmd: "use o agente documentos-pendentes para listar o que o cliente [nome] precisa enviar para fechar [mês/ano]",
  },
  {
    id: 22,
    slug: "onboarding-cliente",
    name: "Onboarding Cliente",
    category: 5,
    categoryName: "Atendimento ao Cliente",
    description: "Onboarding formal de cliente novo — contrato de prestação de serviços (Resolução CFC 803/96 + 1.546/2024), procuração el...",
    whatItDoes: "Onboarding formal de cliente novo — contrato de prestação de serviços (Resolução CFC 803/96 + 1.546/2024), procuração eletrônica e-CAC, termo LGPD (Lei 13.709/2018), coleta de documentos societários, abertura de pasta digital, cadastro no software contábil (Domínio, Sage, Conta Azul, Onvio, Alterdata), conexão e-CAC + portais estadual/municipal + eSocial + FGTS Digital.",
    triggerWhen: ["Cliente acabou de assinar e precisa formalizar a entrada no escritório", "Mencionar contrato contábil, procuração e-CAC, certificado digital, distrato com escritório anterior", "Precisa do fluxo da 1ª semana e do 1º mês", "Quer modelo padronizado de onboarding"],
    notFor: ["Triagem de primeiro contato (use 20)", "Follow-up rotineiro (use 23)"],
    delivery: ["Pacote de onboarding (contrato", "procuração", "LGPD", "termos)", "checklist operacional 1ª semana / 1º mês", "protocolo de transição com escritório anterior", "cadastro no software", "comunicação de boas-vindas"],
    invokeCmd: "use o agente onboarding-cliente para gerar o pacote completo de entrada do cliente [nome] [CNPJ]",
  },
  {
    id: 23,
    slug: "follow-up-cliente",
    name: "Follow-up Cliente",
    category: 5,
    categoryName: "Atendimento ao Cliente",
    description: "Rotina de follow-up com cliente ativo — atualização proativa pós-fechamento mensal (DARFs, DAS, balancete), reunião trim...",
    whatItDoes: "Rotina de follow-up com cliente ativo — atualização proativa pós-fechamento mensal (DARFs, DAS, balancete), reunião trimestral de planejamento tributário, comunicação de mudanças legislativas relevantes, gestão de cliente VIP × comum, retenção anti-churn e reativação de cliente \"frio\".",
    triggerWhen: ["Precisa estruturar régua de comunicação com clientes", "Mencionar follow-up, atualização mensal, comunicação de DARF, NPS, satisfação, retenção, churn, reativação", "Cliente sumiu ou está reclamando", "Quer modelo de e-mail de atualização mensal"],
    notFor: ["Onboarding inicial (use 22)", "Cobrança de honorários atrasados (use 17)"],
    delivery: ["Régua de comunicação por tipo de cliente", "5 modelos prontos (atualização mensal / decisão fiscal favorável / autuação / atraso na declaração / reativação)", "protocolo de reclamação", "métricas NPS", "cronograma trimestral"],
    invokeCmd: "use o agente follow-up-cliente para criar os modelos de comunicação mensal para os clientes VIP do escritório",
  },
  {
    id: 24,
    slug: "cadastro-nf",
    name: "Cadastro de NF",
    category: 6,
    categoryName: "Operação Interna",
    description: "Cadastro e classificação de notas fiscais para escrituração — NF-e (modelo 55), NFS-e (serviço), NFC-e (consumidor final...",
    whatItDoes: "Cadastro e classificação de notas fiscais para escrituração — NF-e (modelo 55), NFS-e (serviço), NFC-e (consumidor final, modelo 65), CT-e (transporte). Identifica CFOP correto, CST/CSOSN, NCM, alíquota ICMS, ICMS-ST, IPI e retenções (ISS, INSS, IRRF, PIS/COFINS quando tomador é PJ obrigada). Detecta NF problemática (CFOP errado, CST inconsistente, divergência XML × PDF).",
    triggerWhen: ["Recebeu lote de NFs e precisa classificar para lançamento", "Mencionar CFOP, NCM, CST/CSOSN, escrituração, importação XML, integração ERP", "NF rejeitada ou divergente entre XML e PDF", "Precisa cadastrar fornecedor ou cliente novo no sistema"],
    notFor: ["Gerar o arquivo SPED Fiscal (use 06)"],
    delivery: ["Planilha de classificação por NF (chave / fornecedor / valor / CFOP / CST / NCM / retenções)", "lista de NFs com problema", "plano de correção", "script de importação XML", "checklist de cadastro de fornecedor"],
    invokeCmd: "use o agente cadastro-nf para classificar as [n] NFs de entrada do cliente [nome] de [mês/ano]",
  },
  {
    id: 25,
    slug: "lembrete-prazo",
    name: "Lembrete de Prazo",
    category: 6,
    categoryName: "Operação Interna",
    description: "Controle de prazos legais do escritório — calendário fiscal mensal (DAS dia 20; GPS dia 20; FGTS dia 20; DARFs último di...",
    whatItDoes: "Controle de prazos legais do escritório — calendário fiscal mensal (DAS dia 20; GPS dia 20; FGTS dia 20; DARFs último dia útil; ICMS varia por UF; ISS varia por município; eSocial S-1299 dia 15; SPED ICMS-IPI dia 25; EFD-Contribuições dia 14 do 2º mês) e declarações anuais (ECF, ECD, DEFIS, IRPF). Cria régua D-7/D-3/D-1/D-0 e calendário ICS importável.",
    triggerWhen: ["Precisa montar calendário fiscal mensal ou anual", "Mencionar prazo, agenda fiscal, vencimento, ICS, antecedência", "Cliente novo precisa do mapa de prazos", "Quer integrar com Google Calendar ou Outlook"],
    notFor: ["Conferência de guia em si (use 05)"],
    delivery: ["Calendário fiscal em CSV", "arquivo ICS importável", "régua D-7/D-3/D-1/D-0", "alertas de feriados", "Python para calcular próxima data útil", "plano de antecipação quando vencimento cai em sábado/domingo/feriado"],
    invokeCmd: "use o agente lembrete-prazo para gerar o calendário fiscal de [mês/ano] para o cliente [nome] em [UF] e [cidade]",
  },
  {
    id: 26,
    slug: "relatorio-mensal",
    name: "Relatório Mensal",
    category: 6,
    categoryName: "Operação Interna",
    description: "Relatório mensal executivo entregue ao cliente — síntese de 1 página com KPIs principais (receita, despesas, lucro, marg...",
    whatItDoes: "Relatório mensal executivo entregue ao cliente — síntese de 1 página com KPIs principais (receita, despesas, lucro, margem, total tributário, % tributação efetiva), evolução vs mês anterior, alertas (autuações, prazos, oportunidades), próximos passos e comentário do contador. Foco em comunicação, não em escrituração técnica.",
    triggerWhen: ["Acabou o fechamento mensal e quer enviar o relatório ao cliente", "Mencionar relatório gerencial, dashboard, KPI, comunicação ao cliente", "Cliente VIP precisa de apresentação executiva", "Quer modelo padronizado para todos os clientes"],
    notFor: ["Balancete técnico (use 42)", "DRE detalhado (use 18)"],
    delivery: ["Relatório de 1 página", "tabela de KPIs", "gráficos textuais (ASCII/sugestões)", "alertas (até 3)", "próximos passos (3-5)", "comentário do contador (3 linhas)", "Python para gerar versão por cliente em batch"],
    invokeCmd: "use o agente relatorio-mensal para gerar o relatório executivo de [mês/ano] do cliente [nome]",
  },
  {
    id: 27,
    slug: "backup-escritorio",
    name: "Backup do Escritório",
    category: 6,
    categoryName: "Operação Interna",
    description: "Política e operação de backup de arquivos do escritório — pastas de clientes, XMLs de NF-e, declarações (ECD/ECF/SPED/EF...",
    whatItDoes: "Política e operação de backup de arquivos do escritório — pastas de clientes, XMLs de NF-e, declarações (ECD/ECF/SPED/EFD), e-mails, contratos, eventos eSocial. Aplica regra 3-2-1 (3 cópias / 2 mídias / 1 off-site), criptografia (LGPD art. 46-47), retenção legal mínima de 5 anos (CC art. 1.194 + CTN art. 173), versionamento, teste mensal de restore e plano de resposta a incidente (LGPD art. 48 — ANPD em 48h).",
    triggerWhen: ["Precisa estruturar a política de backup do escritório", "Mencionar LGPD, ANPD, ransomware, perda de dados, restore, retenção, OneDrive/Drive/Dropbox/AWS", "Sofreu incidente de segurança ou perda de dados", "Está abrindo escritório novo e precisa da infraestrutura"],
    notFor: ["Política operacional do cliente (este agente é para o escritório)"],
    delivery: ["Política de backup escrita", "arquitetura técnica 3-2-1 recomendada", "cronograma de execução automática", "script de teste de restore mensal", "plano de resposta a incidente em 48h", "Termo de Responsabilidade do operador"],
    invokeCmd: "use o agente backup-escritorio para criar a política de backup do escritório com armazenamento no [serviço]",
  },
  {
    id: 28,
    slug: "apuracao-mei",
    name: "Apuração MEI",
    category: 7,
    categoryName: "Especializações",
    description: "MEI — DAS-MEI mensal (PGMEI), DASN-SIMEI anual, controle do limite de faturamento (R$ 81.000/ano), alerta de risco ao se...",
    whatItDoes: "MEI — DAS-MEI mensal (PGMEI), DASN-SIMEI anual, controle do limite de faturamento (R$ 81.000/ano), alerta de risco ao se aproximar de R$ 65k e gerenciamento do desenquadramento com migração para ME no Simples Nacional.",
    triggerWhen: ["Cliente é MEI", "Mencionar PGMEI, DASN-SIMEI, NFS-e nacional, desenquadramento, fator empregado", "Faturamento acumulado do ano superou R$ 65.000", "MEI estourou o limite e precisa migrar"],
    notFor: ["Simples Nacional ME/EPP (use 01)", "MEI Caminhoneiro (regra própria, limite R$ 251.600)"],
    delivery: ["Tabela de controle anual", "DAS gerado", "diagnóstico de risco de desenquadramento", "carta-aviso ao cliente em DOCX/MD se faturamento acumulado > R$ 65k"],
    invokeCmd: "use o agente apuracao-mei para gerar o DAS-MEI de [mês/ano] do cliente [nome] com faturamento de R$ [valor]",
  },
  {
    id: 29,
    slug: "calculo-ipi",
    name: "Cálculo IPI",
    category: 7,
    categoryName: "Especializações",
    description: "Apuração mensal de IPI para indústria e equiparados — TIPI 2022 vigente, regimes de suspensão (drawback, RECOF, encomend...",
    whatItDoes: "Apuração mensal de IPI para indústria e equiparados — TIPI 2022 vigente, regimes de suspensão (drawback, RECOF, encomenda), crédito presumido de exportação (Lei 9.363/96) e Bloco K do SPED.",
    triggerWhen: ["Tem cliente indústria ou equiparado com NF tributada por IPI", "Mencionar suspensão/drawback/RECOF/encomenda/crédito presumido de exportação", "Opera Zona Franca de Manaus ou ALC", "Precisa apurar débitos × créditos de IPI do mês"],
    notFor: [],
    delivery: ["Cálculo Python", "apuração mensal créditos × débitos", "DARF 5123 com vencimento", "memória em CSV", "checklist de 6 itens"],
    invokeCmd: "use o agente calculo-ipi para apurar o IPI de [mês/ano] da indústria [nome] com NCM [código]",
  },
  {
    id: 30,
    slug: "calculo-irrf-folha",
    name: "IRRF na Folha",
    category: 7,
    categoryName: "Especializações",
    description: "IRRF na folha (CLT, pró-labore, RPA, autônomo) e em pagamentos PJ a PF (aluguel, juros, royalties). Aplica tabela progre...",
    whatItDoes: "IRRF na folha (CLT, pró-labore, RPA, autônomo) e em pagamentos PJ a PF (aluguel, juros, royalties). Aplica tabela progressiva 2026, deduções por dependentes (R$ 189,59), pensão alimentícia e INSS deduzido. Controla DARF separado para IRRF do 13º e analisa isenções (aviso prévio indenizado — Súm 463 STJ; férias indenizadas — Tema 481 STJ).",
    triggerWhen: ["Calcula folha CLT e precisa do IRRF correto", "Mencionar DARF 0561, 0588, 3208, dependentes IR ou tabela progressiva", "Trata o 13º salário (requer DARF próprio)", "Verificar se aviso prévio indenizado ou férias indenizadas têm IRRF (não têm)"],
    notFor: [],
    delivery: ["Cálculo Python passo a passo", "DARF correto por natureza (0561/0588/3208)", "análise de não-incidência", "CSV"],
    invokeCmd: "use o agente calculo-irrf-folha para calcular o IRRF do holerite de [nome] com salário bruto R$ [valor] e [n] dependentes",
  },
  {
    id: 31,
    slug: "retencoes-tributarias-tomador",
    name: "Retenções Tributárias (Tomador)",
    category: 7,
    categoryName: "Especializações",
    description: "Retenções que o TOMADOR de serviço deve fazer ao pagar a NF — IRRF 1,5% (código 1708) ou 1% (limpeza/vigilância), CSRF 4...",
    whatItDoes: "Retenções que o TOMADOR de serviço deve fazer ao pagar a NF — IRRF 1,5% (código 1708) ou 1% (limpeza/vigilância), CSRF 4,65% (código 5952, só se acumulado mensal ≥ R$ 215,05), INSS 11% sobre cessão de mão de obra (Lei 8.212 art. 31), ISS retido conforme lei municipal. Identifica quando a declaração de Simples Nacional dispensa a retenção (IN RFB 1.234/2012).",
    triggerWhen: ["Recebeu NF de serviço de PJ para pagar e precisa verificar retenções", "Fornecedor apresentou declaração de Simples Nacional (verifica se dispensa)", "Serviço é cessão de mão de obra (construção, limpeza, vigilância, TI)", "Acumulado mensal próximo a R$ 215,05 (teto para CSRF)"],
    notFor: [],
    delivery: ["Cálculo com cada retenção identificada", "DARFs prontos", "valor líquido a pagar", "comprovantes para o prestador", "guia para EFD-Reinf R-2010/R-4020"],
    invokeCmd: "use o agente retencoes-tributarias-tomador para calcular as retenções da NF de R$ [valor] de [tipo de serviço] do fornecedor [nome]",
  },
  {
    id: 32,
    slug: "efd-contribuicoes",
    name: "EFD-Contribuições",
    category: 7,
    categoryName: "Especializações",
    description: "EFD-Contribuições mensal — escrituração PIS/COFINS por CST (Tabela 4.3.3), Bloco M (apuração), F500 (regime de caixa Luc...",
    whatItDoes: "EFD-Contribuições mensal — escrituração PIS/COFINS por CST (Tabela 4.3.3), Bloco M (apuração), F500 (regime de caixa Lucro Presumido), F600 (CSRF — retenções sofridas), Bloco P (CPRB), conciliação com DCTFWeb.",
    triggerWhen: ["Prepara EFD-Contribuições mensal", "Mencionar PVA EFD-Contrib, M100/M200/M500/M600, CST 50/04/49, F600"],
    notFor: [],
    delivery: ["Validação por amostragem de NFs", "apuração consolidada PIS/COFINS", "cruzamento com DCTFWeb", "checklist de 7 itens"],
    invokeCmd: "use o agente efd-contribuicoes para montar a EFD-Contribuições de [mês/ano] do cliente [nome]",
  },
  {
    id: 33,
    slug: "dimob",
    name: "DIMOB",
    category: 7,
    categoryName: "Especializações",
    description: "DIMOB anual para imobiliárias, construtoras, incorporadoras e administradoras de bens — operações de venda, locação, int...",
    whatItDoes: "DIMOB anual para imobiliárias, construtoras, incorporadoras e administradoras de bens — operações de venda, locação, intermediação e construção. Formata o arquivo TXT para envio pelo PGD conforme IN RFB 1.115.",
    triggerWhen: ["Tem cliente imobiliário que precisa entregar a DIMOB anual", "Mencionar PGD DIMOB, IN RFB 1.115, Operação 01-04, aluguéis repassados, vendas parceladas"],
    notFor: [],
    delivery: ["Tabela de operações por tipo", "arquivo TXT formatado para PGD", "recibo", "comprovante de IRRF a beneficiários"],
    invokeCmd: "use o agente dimob para gerar a DIMOB do exercício [ano] da imobiliária [nome]",
  },
  {
    id: 34,
    slug: "dmed",
    name: "DMED",
    category: 7,
    categoryName: "Especializações",
    description: "DMED anual para prestadores de serviços médicos (hospitais, clínicas, médicos PJ, laboratórios) e operadoras de plano de...",
    whatItDoes: "DMED anual para prestadores de serviços médicos (hospitais, clínicas, médicos PJ, laboratórios) e operadoras de plano de saúde. É o espelho das deduções de saúde no IRPF do paciente — divergência gera malha fina para o paciente.",
    triggerWhen: ["Tem cliente médico, hospital, laboratório ou operadora de plano de saúde", "Mencionar DMED, IN RFB 985, Quadro 12, dependentes plano de saúde"],
    notFor: [],
    delivery: ["Arquivo TXT para PGD", "recibo", "alerta sobre obrigatoriedade do CPF nos recibos médicos"],
    invokeCmd: "use o agente dmed para gerar a DMED do exercício [ano] da clínica [nome]",
  },
  {
    id: 35,
    slug: "folha-pagamento-mensal",
    name: "Folha de Pagamento Mensal",
    category: 7,
    categoryName: "Especializações",
    description: "Folha CLT mensal completa — cálculo de salário base + adicionais (periculosidade, insalubridade, adicional noturno, hora...",
    whatItDoes: "Folha CLT mensal completa — cálculo de salário base + adicionais (periculosidade, insalubridade, adicional noturno, horas extras) + descontos (INSS faixas progressivas, IRRF, VT 6%, plano de saúde, faltas) + FGTS 8% + aplicação do dissídio/CCT vigente. Emite holerite por empregado.",
    triggerWhen: ["Fecha a folha de pagamento do mês", "Mencionar holerite, INSS efetivo, dissídio, periculosidade vs insalubridade, hora reduzida noturna, banco de horas"],
    notFor: [],
    delivery: ["Holerite por empregado em DOCX/MD", "tabela consolidada do mês", "cálculo Python passo a passo", "checklist de 8 itens"],
    invokeCmd: "use o agente folha-pagamento-mensal para processar a folha de [mês/ano] do cliente [nome] com [n] funcionários",
  },
  {
    id: 36,
    slug: "plano-contas-cpc",
    name: "Plano de Contas CPC",
    category: 7,
    categoryName: "Especializações",
    description: "Estruturação do plano de contas com 100% de mapeamento referencial fiscal (Anexo III IN RFB 2.003) e aderência aos CPCs ...",
    whatItDoes: "Estruturação do plano de contas com 100% de mapeamento referencial fiscal (Anexo III IN RFB 2.003) e aderência aos CPCs (CPC 26, 27, 4, 47, 48, 6 R2, 25). Inclui DRE estruturada e provisões mensais (férias, 13º, PCLD).",
    triggerWhen: ["Implanta cliente novo no software contábil", "Abre empresa e precisa do plano de contas inicial", "Migra de ERP e precisa remapear contas", "Recebeu erro de \"conta sem referencial\" no PVA da ECD"],
    notFor: [],
    delivery: ["Plano de contas em CSV com 5 colunas", "matriz de mapeamento referencial", "lista de provisões mensais a configurar no ERP"],
    invokeCmd: "use o agente plano-contas-cpc para criar o plano de contas da empresa [nome] no regime [Presumido/Real/Simples]",
  },
  {
    id: 37,
    slug: "lancamentos-contabeis-padrao",
    name: "Lançamentos Contábeis Padrão",
    category: 7,
    categoryName: "Especializações",
    description: "Catálogo operacional de lançamentos D/C para todas as operações cotidianas — vendas (com impostos como redutor da receit...",
    whatItDoes: "Catálogo operacional de lançamentos D/C para todas as operações cotidianas — vendas (com impostos como redutor da receita bruta), compras (com créditos), folha (encargos e provisões CPC 33), tributos sobre lucro, empréstimos (custo amortizado CPC 48), equivalência patrimonial (CPC 18), PCLD (CPC 48), arrendamento IFRS 16 (CPC 6 R2).",
    triggerWhen: ["Pede modelo de lançamento contábil", "Conferindo livros e tem dúvida sobre a forma correta de um lançamento"],
    notFor: [],
    delivery: ["Lançamentos padronizados D/C com histórico explicativo", "advertência sobre os erros típicos de cada operação"],
    invokeCmd: "use o agente lancamentos-contabeis-padrao para mostrar os lançamentos de [operação] com os impostos corretos",
  },
  {
    id: 38,
    slug: "conciliacao-cartoes-credenciadora",
    name: "Conciliação Cartões / Credenciadora",
    category: 7,
    categoryName: "Especializações",
    description: "Conciliação de vendas via cartão (Cielo, Stone, Rede, GetNet, PagSeguro, SafraPay, Mercado Pago) com os repasses da cred...",
    whatItDoes: "Conciliação de vendas via cartão (Cielo, Stone, Rede, GetNet, PagSeguro, SafraPay, Mercado Pago) com os repasses da credenciadora. Separa MDR (taxa), antecipação, chargebacks, vouchers e PIX QR. Reconhece a receita BRUTA com a taxa como despesa financeira separada (não líquida).",
    triggerWhen: ["Cliente é comércio ou e-commerce com volume de vendas por cartão", "Conciliação mensal divergente entre o relatório da credenciadora e o caixa", "Antecipação de recebíveis de cartão a ser contabilizada"],
    notFor: [],
    delivery: ["Tabela vendas × repasses por data", "classificação por modalidade (débito/crédito/parcelado/pix)", "lançamentos D/C com taxa como despesa financeira"],
    invokeCmd: "use o agente conciliacao-cartoes-credenciadora para conciliar o relatório da [credenciadora] de [mês/ano] do cliente [nome]",
  },
  {
    id: 39,
    slug: "conciliacao-fornecedores",
    name: "Conciliação de Fornecedores",
    category: 7,
    categoryName: "Especializações",
    description: "Conciliação do razão de fornecedores (contas a pagar) — match NFs recebidas × pagamentos × histórico. Identifica NFs em ...",
    whatItDoes: "Conciliação do razão de fornecedores (contas a pagar) — match NFs recebidas × pagamentos × histórico. Identifica NFs em duplicidade, adiantamentos (separar em 1.1.5), retenções de NF de serviço (lançar passivo IRRF/CSRF/INSS retido), juros/multa e descontos por pagamento antecipado.",
    triggerWhen: ["Fecha mês (foco nos 20 maiores fornecedores)", "Em auditoria com necessidade de circularização", "Cliente novo com histórico de contas a pagar não conciliadas"],
    notFor: [],
    delivery: ["Planilha por fornecedor com saldo apurado × razão contábil", "modelo de circularização para os top fornecedores"],
    invokeCmd: "use o agente conciliacao-fornecedores para conciliar os 20 maiores fornecedores do cliente [nome] em [mês/ano]",
  },
  {
    id: 40,
    slug: "conciliacao-clientes",
    name: "Conciliação de Clientes",
    category: 7,
    categoryName: "Especializações",
    description: "Conciliação do razão de clientes (contas a receber) — match NFs emitidas × recebimentos. Monta aging (a vencer / 1-30 / ...",
    whatItDoes: "Conciliação do razão de clientes (contas a receber) — match NFs emitidas × recebimentos. Monta aging (a vencer / 1-30 / 31-60 / 61-90 / 91-180 / > 180 / > 360 dias). Calcula PCLD por modelo de perdas esperadas (CPC 48) e orienta baixa fiscal por perda (Lei 9.430/96 art. 9-14).",
    triggerWhen: ["Fecha balancete e precisa conferir o saldo de clientes", "Revisa a carteira de recebíveis", "Precisa atualizar a PCLD ou dar baixa fiscal em créditos irrecuperáveis"],
    notFor: [],
    delivery: ["Tabela de aging completa", "cálculo de PCLD por estágio (CPC 48)", "ajuste contábil a lançar"],
    invokeCmd: "use o agente conciliacao-clientes para montar o aging de contas a receber do cliente [nome] em [mês/ano]",
  },
  {
    id: 41,
    slug: "fechamento-mensal",
    name: "Fechamento Mensal",
    category: 7,
    categoryName: "Especializações",
    description: "Roteiro completo de fechamento contábil mensal em até 5 dias úteis — provisões (CPC 33: férias, 13º, PCLD), depreciação,...",
    whatItDoes: "Roteiro completo de fechamento contábil mensal em até 5 dias úteis — provisões (CPC 33: férias, 13º, PCLD), depreciação, conciliações (banco/cartão/fornecedores/clientes), encerramento de resultado mensal e geração de relatórios (balancete, DRE, BP, DFC CPC 03).",
    triggerWhen: [],
    notFor: [],
    delivery: ["Checklist mestre de fechamento", "balancete", "DRE", "DFC", "pacote analítico ao cliente em DOCX/MD"],
    invokeCmd: "use o agente fechamento-mensal para guiar o fechamento de [mês/ano] do cliente [nome]",
  },
  {
    id: 42,
    slug: "balancete-analise",
    name: "Balancete — Análise",
    category: 7,
    categoryName: "Especializações",
    description: "Leitura e análise do balancete mensal — verifica integridade (D = C, sintética = soma das analíticas), coerência (saldo ...",
    whatItDoes: "Leitura e análise do balancete mensal — verifica integridade (D = C, sintética = soma das analíticas), coerência (saldo invertido, conta com natureza errada), variações > 20% vs mês anterior e calcula indicadores (liquidez corrente, endividamento, PMR, PMP, giro de estoque, ROE).",
    triggerWhen: [],
    notFor: [],
    delivery: ["Pacote analítico estruturado", "alertas de inconsistência", "recomendações de ajuste"],
    invokeCmd: "use o agente balancete-analise para revisar o balancete de [mês/ano] do cliente [nome]",
  },
  {
    id: 43,
    slug: "ativo-imobilizado-depreciacao",
    name: "Ativo Imobilizado / Depreciação",
    category: 7,
    categoryName: "Especializações",
    description: "Ativo imobilizado (CPC 27) — reconhecimento (custo + frete + montagem + tributos não-recuperáveis), depreciação (linear,...",
    whatItDoes: "Ativo imobilizado (CPC 27) — reconhecimento (custo + frete + montagem + tributos não-recuperáveis), depreciação (linear, soma dos dígitos, unidades produzidas, acelerada por turnos RIR 322), vida útil contábil × fiscal (Anexo III IN 1.700), valor residual (revisão anual), impairment (CPC 1), CIAP (48 parcelas ICMS imobilizado), intangíveis (CPC 4), arrendamento IFRS 16 / CPC 6 R2.",
    triggerWhen: ["Empresa compra ou vende imobilizado", "Revisão anual de vida útil e valor residual", "Teste de impairment obrigatório (CPC 1)", "Novo contrato de arrendamento/locação (IFRS 16)"],
    notFor: [],
    delivery: ["Cadastro do bem com todos os atributos", "cálculo de depreciação mensal", "lançamentos D/C", "alerta de impairment se aplicável"],
    invokeCmd: "use o agente ativo-imobilizado-depreciacao para cadastrar o bem [descrição] adquirido por R$ [valor] com vida útil de [n] anos",
  },
  {
    id: 44,
    slug: "analise-tributaria-regime",
    name: "Análise de Regime Tributário",
    category: 7,
    categoryName: "Especializações",
    description: "Análise comparativa Simples Nacional × Lucro Presumido × Lucro Real com projeção de 12 meses. Considera ICMS, ISS, PIS/C...",
    whatItDoes: "Análise comparativa Simples Nacional × Lucro Presumido × Lucro Real com projeção de 12 meses. Considera ICMS, ISS, PIS/COFINS, IRPJ/CSLL e INSS/CPP. Inclui análise de sensibilidade ±20% no faturamento e margem.",
    triggerWhen: ["Início do ano-calendário (Simples: até último dia útil de janeiro; Real/Presumido: 1ª DARF)", "Mudança relevante na empresa (novos sócios, nova atividade, expansão, queda de margem)", "Empresa próxima a estourar o limite do Simples (R$ 4,8 mi)", "Margem real menor que a margem presumida (pode indicar Lucro Real mais vantajoso)"],
    notFor: [],
    delivery: ["Comparativo com 3 cenários (Simples × Presumido × Real)", "análise de sensibilidade ±20%", "recomendação assinada por contador (CRC)"],
    invokeCmd: "use o agente analise-tributaria-regime para comparar os regimes da empresa [nome] com faturamento de R$ [valor]/ano e margem de [%]",
  },
  {
    id: 45,
    slug: "recuperacao-creditos-pis-cofins",
    name: "Recuperação Créditos PIS/COFINS",
    category: 7,
    categoryName: "Especializações",
    description: "Recuperação retroativa de PIS/COFINS pagos a maior nos últimos 5 anos — Tema 69 STF (exclusão ICMS retroativa, modulação...",
    whatItDoes: "Recuperação retroativa de PIS/COFINS pagos a maior nos últimos 5 anos — Tema 69 STF (exclusão ICMS retroativa, modulação 15/03/2017), Tema 779 STJ (insumos amplos), monofásicos tributados indevidamente, créditos de exportação não aproveitados, crédito presumido sobre estoque (Lei 10.637 art. 11).",
    triggerWhen: ["Cliente Lucro Real com mais de 5 anos de operação", "Cliente Lucro Presumido com Tema 69 retroativo (modulação 15/03/2017)", "Trabalho de revisão fiscal pré ou pós due diligence"],
    notFor: [],
    delivery: ["Memória de cálculo mês a mês com Selic", "EFD-Contribuições retificadora", "PER/DCOMP", "acompanhamento da restituição"],
    invokeCmd: "use o agente recuperacao-creditos-pis-cofins para levantar créditos retroativos do cliente [nome] de [ano início] a [ano fim]",
  },
  {
    id: 46,
    slug: "revisao-fiscal-cruzamento-sped",
    name: "Revisão Fiscal / Cruzamento SPED",
    category: 7,
    categoryName: "Especializações",
    description: "Cruzamento ECD × ECF × EFD ICMS/IPI × EFD-Contribuições × eSocial × EFD-Reinf × DCTFWeb para identificar divergências an...",
    whatItDoes: "Cruzamento ECD × ECF × EFD ICMS/IPI × EFD-Contribuições × eSocial × EFD-Reinf × DCTFWeb para identificar divergências antes da malha fina ou em diligência. Classifica por valor e criticidade.",
    triggerWhen: ["Auditoria interna trimestral preventiva", "Antes de transmitir a ECF (após gerar a ECD)", "Due diligence em processo de M&A", "Intimação recebida ou suspeita de divergência entre obrigações"],
    notFor: [],
    delivery: ["Espelho de divergências classificado por valor e criticidade", "plano de ajuste com retificações na ordem correta (EFD → ECD → ECF → DCTFWeb)"],
    invokeCmd: "use o agente revisao-fiscal-cruzamento-sped para cruzar todas as obrigações do cliente [nome] de [ano]",
  },
  {
    id: 47,
    slug: "malha-fina-pf-diagnostico",
    name: "Malha Fina PF",
    category: 7,
    categoryName: "Especializações",
    description: "Diagnóstico de pendências de IRPF na malha fina — interpreta o extrato do e-CAC (Meu IRPF), identifica a causa (rendimen...",
    whatItDoes: "Diagnóstico de pendências de IRPF na malha fina — interpreta o extrato do e-CAC (Meu IRPF), identifica a causa (rendimento omitido, dedução indevida, dependente, ganho de capital), decide se é caso de retificadora ou defesa via e-CAC (prazo 30 dias), e prepara o documento correto.",
    triggerWhen: ["Cliente PF recebeu comunicado de pendência de IRPF", "Intimação ou notificação da Receita Federal referente ao IRPF", "Verificação preventiva após entrega da declaração"],
    notFor: [],
    delivery: ["Extrato decifrado", "decisão (retificar ou defender)", "retificadora ou minuta de defesa", "DARF código 0211 com Selic", "multa se aplicável"],
    invokeCmd: "use o agente malha-fina-pf-diagnostico para analisar a pendência do cliente [nome] referente ao IRPF de [ano]",
  },
  {
    id: 48,
    slug: "malha-fina-pj-diagnostico",
    name: "Malha Fina PJ",
    category: 7,
    categoryName: "Especializações",
    description: "Diagnóstico de intimações da malha PJ — TIF (Termo de Intimação Fiscal — 20 dias), Comunicado de Inconsistência, Auto de...",
    whatItDoes: "Diagnóstico de intimações da malha PJ — TIF (Termo de Intimação Fiscal — 20 dias), Comunicado de Inconsistência, Auto de Infração (30 dias para impugnar ao DRJ), Despacho Decisório, Aviso de Lançamento. Identifica divergências entre os SPEDs e a DCTFWeb.",
    triggerWhen: ["Empresa recebeu intimação da RFB, Sefaz ou prefeitura", "Pendência de regularidade na Certidão Negativa de Débitos (CND)", "Suspeita preventiva de divergência antes de pedir a CND"],
    notFor: [],
    delivery: ["Documento decifrado", "plano (retificar / defender / parcelar)", "minuta de resposta", "cronograma das ações"],
    invokeCmd: "use o agente malha-fina-pj-diagnostico para analisar o auto de infração recebido pela empresa [nome]",
  },
  {
    id: 49,
    slug: "due-diligence-contabil",
    name: "Due Diligence Contábil",
    category: 7,
    categoryName: "Especializações",
    description: "Due diligence contábil-fiscal-trabalhista pré-M&A ou pré-investimento (VC/PE) — identifica passivos ocultos, contingênci...",
    whatItDoes: "Due diligence contábil-fiscal-trabalhista pré-M&A ou pré-investimento (VC/PE) — identifica passivos ocultos, contingências (CPC 25), ajusta o EBITDA (Quality of Earnings). Relatório de findings classificado por severidade (alta/média/baixa). Escopo de 4 a 12 semanas com cut-off date e materialidade definidos.",
    triggerWhen: ["Compra/venda de empresa, fusão ou aporte de capital", "Expansão por franquia, sucessão familiar ou herança", "NDA assinado e data room aberto para auditoria"],
    notFor: [],
    delivery: ["Findings classificados por severidade", "EBITDA ajustado", "cláusulas de R&W (Rep & Warranties)", "escrow sugerido", "relatório final assinado"],
    invokeCmd: "use o agente due-diligence-contabil para iniciar a DD da empresa [nome] com escopo [fiscal/trabalhista/full] e cut-off [data]",
  },
  {
    id: 50,
    slug: "valuation-pme",
    name: "Valuation PME",
    category: 7,
    categoryName: "Especializações",
    description: "Valuation de PME por 3 métodos: DCF (FCFF/FCFE com projeção 5 anos), múltiplos comparáveis (EV/EBITDA, EV/Receita, P/E) ...",
    whatItDoes: "Valuation de PME por 3 métodos: DCF (FCFF/FCFE com projeção 5 anos), múltiplos comparáveis (EV/EBITDA, EV/Receita, P/E) e patrimonial (piso). Ajusta o EBITDA com one-offs, calcula WACC com prêmio Brasil + tamanho e aplica sensibilidade WACC × g.",
    triggerWhen: ["Cliente quer vender a empresa ou captar investidor", "Sucessão familiar ou partilha em processo de divórcio", "Combinação de negócios (CPC 15) — aquisição com ágio/deságio"],
    notFor: [],
    delivery: ["Faixa de valor (mínimo-médio-máximo)", "planilha DCF", "análise de sensibilidade", "relatório assinado"],
    invokeCmd: "use o agente valuation-pme para avaliar a empresa [nome] com EBITDA de R$ [valor] e crescimento esperado de [%] ao ano",
  },
  {
    id: 51,
    slug: "irpf-declaracao-completa",
    name: "IRPF — Declaração Completa",
    category: 7,
    categoryName: "Especializações",
    description: "Declaração de IRPF anual completa — múltiplas fontes (CLT, autônomo, aluguel, ganho de capital, B3, exterior Lei 14.754/...",
    whatItDoes: "Declaração de IRPF anual completa — múltiplas fontes (CLT, autônomo, aluguel, ganho de capital, B3, exterior Lei 14.754/2023, atividade rural), comparativo Simplificada × Completa (desconto simplificado R$ 564,80 ou deduções legais), dependentes (CPF obrigatório), bens e direitos em 31/12 e dívidas > R$ 5.000.",
    triggerWhen: ["Período de entrega do IRPF (15/03 a 31/05 do ano seguinte)", "Precisa entregar retificadora de IRPF"],
    notFor: [],
    delivery: ["Declaração simulada Simplificada × Completa", "DARFs (cota única ou parcelas)", "lista de bens em 31/12", "comprovação documental necessária"],
    invokeCmd: "use o agente irpf-declaracao-completa para preparar a declaração de IRPF de [ano-base] do cliente [nome]",
  },
  {
    id: 52,
    slug: "abertura-empresa-cnpj",
    name: "Abertura de Empresa / CNPJ",
    category: 7,
    categoryName: "Especializações",
    description: "Abertura de empresa via REDESIM (Lei 14.195/2021) — viabilidade de nome + endereço × CNAE, coleta do DBE (inscrições na ...",
    whatItDoes: "Abertura de empresa via REDESIM (Lei 14.195/2021) — viabilidade de nome + endereço × CNAE, coleta do DBE (inscrições na RFB, Estado, Município, Bombeiros, Anvisa), contrato social com cláusulas obrigatórias (CC 997), registro na Junta Comercial e opção tributária.",
    triggerWhen: ["Cliente vai abrir empresa nova ou segunda empresa", "Mencionar REDESIM, NIRE, MEI, ME, EPP, LTDA, SLU"],
    notFor: [],
    delivery: ["Checklist completo", "cronograma de 5-15 dias", "minuta de contrato social", "plano de contas implantado"],
    invokeCmd: "use o agente abertura-empresa-cnpj para abrir uma [LTDA/SLU] de [atividade] em [cidade/UF]",
  },
  {
    id: 53,
    slug: "alteracao-contratual",
    name: "Alteração Contratual",
    category: 7,
    categoryName: "Especializações",
    description: "Alterações contratuais via REDESIM — entrada/saída de sócios (cessão onerosa com DARF GCAP código 4600 ou cessão gratuit...",
    whatItDoes: "Alterações contratuais via REDESIM — entrada/saída de sócios (cessão onerosa com DARF GCAP código 4600 ou cessão gratuita com ITCMD), aumento/redução de capital, mudança de objeto/CNAE, mudança de endereço (UF nova exige nova IE), transformação societária (LTDA ↔ S.A. mantém o CNPJ).",
    triggerWhen: ["Muda o quadro societário, a atividade, o endereço ou o capital social", "Faz transformação societária"],
    notFor: [],
    delivery: ["Cláusulas da alteração", "DBE atualizado", "DARF GCAP se cessão onerosa", "comunicação formal a bancos e fornecedores"],
    invokeCmd: "use o agente alteracao-contratual para redigir a alteração de entrada do sócio [nome] na empresa [nome]",
  },
  {
    id: 54,
    slug: "encerramento-empresa-baixa",
    name: "Encerramento / Baixa",
    category: 7,
    categoryName: "Especializações",
    description: "Baixa de empresa via REDESIM — baixa regular (sem dívidas) ou com débito (Lei 11.598/07 art. 7º-A — débitos passam aos s...",
    whatItDoes: "Baixa de empresa via REDESIM — baixa regular (sem dívidas) ou com débito (Lei 11.598/07 art. 7º-A — débitos passam aos sócios), distrato social com liquidante, encerramento contábil (realizar ativo, pagar passivo, distribuir acervo), declarações fracionadas (ECF/ECD/DEFIS/DCTFWeb/EFDs/eSocial S-2299/Reinf) e ganho de capital do sócio na restituição.",
    triggerWhen: ["Cliente vai encerrar a empresa", "Empresa parada acumulando obrigações sem atividade"],
    notFor: [],
    delivery: ["Distrato social", "cronograma de baixa", "lista de declarações fracionadas a entregar", "plano de comunicação aos credores"],
    invokeCmd: "use o agente encerramento-empresa-baixa para estruturar a baixa da empresa [nome]",
  },
  {
    id: 55,
    slug: "parcelamento-receita-federal",
    name: "Parcelamento Receita Federal",
    category: 7,
    categoryName: "Especializações",
    description: "Parcelamentos federais — ordinário 60x (Lei 10.522/2002, multa reduzida 50%), simplificado online (até R$ 5 mi por débit...",
    whatItDoes: "Parcelamentos federais — ordinário 60x (Lei 10.522/2002, multa reduzida 50%), simplificado online (até R$ 5 mi por débito), transação tributária (Lei 13.988/2020 — descontos até 65%, 145 meses), recuperação judicial tributária (Lei 14.112/2020, 120 meses) e programas pontuais (PERSE, PERT, PRR).",
    triggerWhen: ["Cliente tem débitos federais e não tem caixa para pagar à vista", "Quer trocar dívida cara por dívida estruturada com Selic", "Quer aproveitar descontos da PGFN em transação tributária"],
    notFor: [],
    delivery: ["Simulação de cenários (à vista vs ordinário vs transação)", "adesão passo a passo", "DARFs mensais"],
    invokeCmd: "use o agente parcelamento-receita-federal para simular as opções de parcelamento de R$ [valor] de [tipo de débito] da empresa [nome]",
  },
  {
    id: 56,
    slug: "resposta-fiscalizacao-intimacao",
    name: "Resposta a Fiscalização",
    category: 7,
    categoryName: "Especializações",
    description: "Resposta a fiscalização federal/estadual/municipal — TIF (20 dias), Auto de Infração (30 dias para impugnar ao DRJ), Des...",
    whatItDoes: "Resposta a fiscalização federal/estadual/municipal — TIF (20 dias), Auto de Infração (30 dias para impugnar ao DRJ), Despacho Decisório (30 dias), Aviso de Lançamento. Levanta decadência (CTN 173), prescrição (CTN 174), denúncia espontânea (CTN 138 — sem multa antes da fiscalização) e redução de multa qualificada (150% → 75% sem dolo).",
    triggerWhen: ["Empresa recebeu MPF, TIF, auto de infração, despacho decisório ou aviso de lançamento", "Precisa pedir prorrogação de prazo", "Prepara impugnação ao DRJ ou recurso ao CARF"],
    notFor: [],
    delivery: ["Minuta de resposta com fundamentação legal", "cronograma de prazos", "protocolo de envio via e-CAC"],
    invokeCmd: "use o agente resposta-fiscalizacao-intimacao para responder o auto de infração [número] de [data] contra a empresa [nome]",
  },
  {
    id: 57,
    slug: "reforma-tributaria-cbs-ibs",
    name: "Reforma Tributária — CBS/IBS",
    category: 7,
    categoryName: "Especializações",
    description: "Especialista na Reforma Tributária sobre o Consumo (EC 132/2023 + LC 214/2025) — CBS (substitui PIS/COFINS/IPI), IBS (su...",
    whatItDoes: "Especialista na Reforma Tributária sobre o Consumo (EC 132/2023 + LC 214/2025) — CBS (substitui PIS/COFINS/IPI), IBS (substitui ICMS/ISS), Imposto Seletivo (IS), regime de transição 2026-2032, regimes diferenciados (saúde, educação, transporte coletivo, agro), não-cumulatividade ampla com crédito financeiro, cashback, split payment e Comitê Gestor do IBS.",
    triggerWhen: ["Simular impacto da Reforma Tributária no negócio do cliente", "Mencionar CBS, IBS, IS, EC 132, LC 214, split payment, cashback, transição tributária, alíquota teste 2026 (0,9% CBS + 0,1% IBS)", "Cliente quer planejamento tributário para 2026-2033", "Precisa de parecer sobre regime diferenciado"],
    notFor: ["Apuração Simples pré-Reforma (use 01)", "Lucro Real pré-Reforma (use 03)", "ICMS isolado (use 02)", "PIS/COFINS isolado (use 03)"],
    delivery: ["Simulação paralela (regime atual × CBS/IBS) por ano de transição em CSV", "identificação de regime diferenciado aplicável", "matriz de impacto crédito-débito", "plano de adequação 2026-2033", "checklist operacional (NF, contabilidade, fluxo de caixa, sistema)"],
    invokeCmd: "use o agente reforma-tributaria-cbs-ibs para simular o impacto da Reforma no cliente [nome] com faturamento de R$ [valor] e atividade [tipo]",
  }
];